CC=gcc
CFLAGS=-std=c99

all: aufgabe3_childrenpipe aufgabe10_yesterday

aufgabe3_childrenpipe: aufgabe3_childrenpipe.c
aufgabe10_yesterday:  aufgabe10_yesterday.c

clean:
	rm -f aufgabe8_vendors aufgabe8_vendors_alternative aufgabe2_stackmutex aufgabe3_childrenpipe aufgabe9_signaltimer aufgabe10_tomorrow